<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Areas\Facturacion\Views\Cliente\**" />
    <Content Remove="Areas\Facturacion\Views\Cliente\**" />
    <EmbeddedResource Remove="Areas\Facturacion\Views\Cliente\**" />
    <None Remove="Areas\Facturacion\Views\Cliente\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="log4net.config" />
    <Content Remove="Views\Shared\_ModalTecladoDemo.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\Facturacion\Data\" />
    <Folder Include="Areas\Facturacion\Models\" />
    <Folder Include="Areas\Seguridad\Data\" />
    <Folder Include="Areas\Seguridad\Models\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="log4net.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="Views\Home\_ModalTecladoDemo.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="3.3.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.8" />
    <PackageReference Include="Microsoft.Extensions.Logging.Log4Net.AspNetCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.23" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.7.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\gc.caja.core\gc.caja.core.csproj" />
    <ProjectReference Include="..\gc.infraestructura\gc.infraestructura.csproj" />
  </ItemGroup>

</Project>
