namespace gc.infraestructura.Enumeraciones
{
    public enum AppModulos
    {
        CCUENTAS, //CONSULTA DE CUENTAS COMERCIALES
        ASTEMP, //ASIENTOS TEMPORALES
        ASDEF, //ASIENTOS DEFINITIVOS
        LMAYOR, //LIBRO MAYOR,
        BSS, //BALANCE SUMA SALDOS
        LDIARIO, //LIBRO DIARIO
        BGR, //BALANCE GENERAL
        OPP, //ORDEN DE PAGO A PROVEEDOR
        CERTRETENIIBB, //CERTIFICADO DE RETENCION DE IIBB
		CERTRETENGA, //CERTIFICADO DE RETENCION DE GA
		CERTRETENIVA, //CERTIFICADO DE RETENCION DE IVA
        ASXAJUSTE, //ASIENTO POR AJUSTE DE INFLACION
		OPD, //ORDEN DE PAGO DIRECTA
        COP, //CONSULTA DE ORDENES DE PAGO
		OC, //ORDEN DE COMPRA
		TEC, //TRANSFERENCIA ENTRE CUENTAS
        CMF, //CONSULTA DE MOVIMIENTOS FINANCIEROS
        VCE, //VENCIMIENTO DE CHEQUES EMITIDOS
        LBD, //LIBRO DE BANCOS DETALLE
        LBR, //LIBRO DE BANCOS RESUMEN
        HLI, //HISTORICO LIBRO
        EBA, //EXTRACTO BANCARIO
        OF_SINACT, //OFERTAS SIN ACTIVAR
        OF_ACT, //OFERTAS SIN ACTIVAR
        PROMO_COMBO, //PROMOCIONES Y COMBO
        PRESUP, //PRESUPUESTO
        CPE, // CHEQUES PROPIOS EMITIDOS
		PDI, // PROYECCIÓN DE INGRESO
		SDC, // SALDO DE CUENTAS
		FDI, // FLUJO DE INGRESOS
		PDE, // PROYECCIÓN DE EGRESOS
        ADE, // ANTICIPO DE EMPLEADOS
		DDA, // DETALLE DE ANTICIPO
		DDH, // DETALLE DE LIQUIDACION DE HABERES
        ETIQUETAS, // ETIQUETAS PRECIO DE PRODUCTOS    
		CV_TC_TC, // CONSULTA VENCIMIENTO POR TIPO DE CUENTA Y TIPO DE COMPROBANTE
		CC_NR_NP, // CONSULTA DE CERTIFICADO DE NO RETENCION NO PERCEPCION 
        PRECIO_LISTA, // PRECIO DE LISTA DE PRODUCTOS
		REPORTE_STOCK, // REPORTE DE STOCK
        IMPOSITIVO, // DATOS IMPOSITIVOS
		REPORTE_STOCK_VALORIZADO, // REPORTE DE STOCK VALORIZADOS
        OF_REPORTE, //REPORTE DE OFERTAS Y COMBOS
		REPORTE_STOCK_COMPENSADO, // REPORTE DE STOCK COMPENSADO
        REPORTE_TRACE, // REPORTE TRACE
        PROVEEDOR_SIN_MODIFICACIONES, // PROVEEDORES SIN MODIFICACIONES
		INV_REPO_STK_VS_CONTEO, // REPORTE DE STOCK VS CONTEO
		INV_REPO_VAL_X_SEC, // REPORTE DE VALORIZACION POR SECTOR
		INV_REPO_VAL_X_RUB, // REPORTE DE VALORIZACION POR RUBRO
		INV_REPO_VAL_DETALLE, // REPORTE DE VALORIZACION DETALLE
		INV_REPO_CONTEO_X_USU, // REPORTE DE CONTEO POR USUARIO
        PEDIDO_DE_CLIENTE, // REPORTE DE PEDIDO DE CLIENTE
		ORDEN_DE_REPARTO_HOJA_DE_RUTA, // REPORTE DE HOJA DE RUTA DE ORDEN DE REPARTO
		ORDEN_DE_REPARTO_HOJA_DE_PRODUCTO, // REPORTE DE HOJA DE PRODUCTO DE ORDEN DE REPARTO
		PEDIDO_INTERNO, // PEDIDO INTERNO
		PEDIDO_INTERNO_LISTA, // PEDIDO INTERNO LISTADO
		ANALISIS_VENTA_MENSUAL, //ANALISIS VENTA MENSUAL
		ANALISIS_VENTA_DIARIO, //ANALISIS VENTA DIARIO
		ANALISIS_VENTA_OP_VTA_DIARIO, //ANALISIS VENTA OPERATIVO DE VENTA DIARIO
		ANALISIS_VENTA_SUCURSAL, //ANALISIS VENTA SUCURSAL
		ANALISIS_VENTA_CIERRES, //ANALISIS VENTA CIERRES
		ANALISIS_VENTA_ANUAL, //ANALISIS VENTA ANUAL
		ANALISIS_DE_VALORES_DE_VENTA_MENSUAL, //ANALISIS DE VALORES DE VENTA MENSUAL
		ANALISIS_DE_VALORES_DE_VENTA_DIARIO, //ANALISIS DE VALORES DE VENTA DIARIO
		ANALISIS_DE_VALORES_DE_VENTA_PV, //ANALISIS DE VALORES DE VENTA PV
		ANALISIS_DE_VALORES_DE_VENTA_CASHBACK, //ANALISIS DE VALORES DE VENTA CB
		REPORTE_RECEPCION_PROVEEDORES, // REPORTE DE RECEPCION DE PROVEEDORES
		REPORTE_RECEPCION_PROVEEDORES_DETALLE, // REPORTE DE RECEPCION DE PROVEEDORES DETALLE
		SORTEO_COMPROBANTES_CONSULTA, // REPORTE DE COMPROBANTES DE SORTEO
		SORTEO_ANALISIS_DE_PRODUCTOS, // REPORTE DE ANALISIS DE PRODUCTOS DE SORTEO
        REPORTE_RENDICION_CIERRE, // REPORTE DE RENDICION DE CIERRES DE CAJA
        REPORTE_ANALITICO_OPERACION, // REPORTE DE ANALISIS ANALITICO DE OPERACIONES
		CONS_CTA_CORRIENTE_FINANCIERA, // CONSULTA DE CUENTA CORRIENTE FINANCIERA
		DETALLE_VALORES_EN_CARTERA, // DETALLE DE VALORES EN CARTERA
		MOVIMIENTO_DE_CUENTAS_DIRECTAS, // MOVIMIENTO DE CUENTAS DIRECTAS
	}

    public enum AppReportes
    {
        CCUENTAS_CUENTA_CORRIENTE = 1,
        CCUENTAS_VENCIMIENTO_COMPROBANTES = 2,
        CCUENTAS_COMPROBANTES = 3,
        CCUENTAS_ORDEN_DE_PAGO = 4,
        CCUENTAS_RECEPCION_PROVEEDORES = 5,
        CCUENTAS_COMPROBANTES_DETALLE = 6,
        CCUENTAS_ORDEN_DE_PAGO_DETALLE = 7,
        CCUENTAS_RECEPCION_PROVEEDORES_DETALLE = 8,
    }

    public enum DocumentType
    {
        Original,
        Duplicate,
        Certificate,
        Receipt,
        Report,
        Statement
    }

    public enum ExportType
    {
        PDF,
        Excel,
        TXT
    }

    public enum MessagePriority
    {
        Low,
        Normal,
        High
    }
}
